version: "3.1"
services:
    nginx:
      build:
        context: .
        args:
          GIT_DEPLOYED_SHA: abc123
      container_name: usafb-ui-nginx
      volumes:
          - .:/application
      environment:
        - USAFB_API_URL=http://docker.for.mac.localhost:8000
      ports:
       - "8080:80"
       - "443"
